server:
  port: 8762

spring:
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    discovery:
      enabled: true
      serviceId: "CONFIG-SERVER"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}