spring:
  application:
    name: demo
  config:
    import: "optional:configserver:"
  cloud:
    discovery:
      enabled: true
      serviceId: "CONFIG-SERVER"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}