spring:
  application:
    name: demo

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka



management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"