spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      routes:
        - id: first-service # ???? ?? id??? ??? ???? ??
          predicates: # ??
            - Path=/wow/**
          uri: lb://DEMO
          filters:
            - RewritePath=/wow/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"